### ISSUE TITLE
MP error correction

### ISSUE THREAD

**Issue by ptranvan** [macmanes-lab/Geosmithia_manuscript#1]
Hi,

Why you didn't applied BLESS on Mate pair data ?

**Comment by tarunaaggarwal** [comment]
Hi. We used a different error correction tool for MP reads because I believe BLESS works well with PE reads only.

**Comment by ptranvan** [comment]
So you are using only Nextclip for MP ?
Do you think it's worth running Trimmomatic after Nextclip ?

**Comment by tarunaaggarwal** [comment]
Yes we used Nextclip only for MP. No I don't think you need to run Trimmomatic, but my advisor always says try everything and see what you get. If you have time, you can do the following:
1. Trim with Nextclip only
2. Trim with Trimmomatic only
3. Trim with Nextclip followed by Trimmomatic

But I would just stick with one  trimming personally. At the least, you can compare the two trimming tools. Up to you! Option 3 is unusual in my opinion.
